# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gm.proto',
  package='PrivateProto',
  syntax='proto2',
  serialized_pb=_b('\n\x08gm.proto\x12\x0cPrivateProto\"\x13\n\x04Ping\x12\x0b\n\x03msg\x18\x01 \x02(\t\"\x13\n\x04Pong\x12\x0b\n\x03msg\x18\x02 \x02(\t\"F\n\x08\x41\x64\x64Money\x12\x0c\n\x04tuid\x18\x01 \x02(\x04\x12\x0c\n\x04\x63uid\x18\x02 \x02(\x04\x12\x0e\n\x06money1\x18\x03 \x02(\x05\x12\x0e\n\x06money2\x18\x04 \x02(\x05\")\n\x0bRetAddMoney\x12\x0c\n\x04tuid\x18\x01 \x02(\x04\x12\x0c\n\x04\x63uid\x18\x02 \x02(\x04\"-\n\tSetNotice\x12\x0f\n\x07notice1\x18\x01 \x02(\t\x12\x0f\n\x07notice2\x18\x02 \x02(\t\"6\n\x12SetCustomerService\x12\x0f\n\x07wechat1\x18\x01 \x02(\t\x12\x0f\n\x07wechat2\x18\x02 \x02(\t')
)




_PING = _descriptor.Descriptor(
  name='Ping',
  full_name='PrivateProto.Ping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='PrivateProto.Ping.msg', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=45,
)


_PONG = _descriptor.Descriptor(
  name='Pong',
  full_name='PrivateProto.Pong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='PrivateProto.Pong.msg', index=0,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=66,
)


_ADDMONEY = _descriptor.Descriptor(
  name='AddMoney',
  full_name='PrivateProto.AddMoney',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tuid', full_name='PrivateProto.AddMoney.tuid', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cuid', full_name='PrivateProto.AddMoney.cuid', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='money1', full_name='PrivateProto.AddMoney.money1', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='money2', full_name='PrivateProto.AddMoney.money2', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=138,
)


_RETADDMONEY = _descriptor.Descriptor(
  name='RetAddMoney',
  full_name='PrivateProto.RetAddMoney',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tuid', full_name='PrivateProto.RetAddMoney.tuid', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cuid', full_name='PrivateProto.RetAddMoney.cuid', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=181,
)


_SETNOTICE = _descriptor.Descriptor(
  name='SetNotice',
  full_name='PrivateProto.SetNotice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='notice1', full_name='PrivateProto.SetNotice.notice1', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='notice2', full_name='PrivateProto.SetNotice.notice2', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=228,
)


_SETCUSTOMERSERVICE = _descriptor.Descriptor(
  name='SetCustomerService',
  full_name='PrivateProto.SetCustomerService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wechat1', full_name='PrivateProto.SetCustomerService.wechat1', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wechat2', full_name='PrivateProto.SetCustomerService.wechat2', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=284,
)

DESCRIPTOR.message_types_by_name['Ping'] = _PING
DESCRIPTOR.message_types_by_name['Pong'] = _PONG
DESCRIPTOR.message_types_by_name['AddMoney'] = _ADDMONEY
DESCRIPTOR.message_types_by_name['RetAddMoney'] = _RETADDMONEY
DESCRIPTOR.message_types_by_name['SetNotice'] = _SETNOTICE
DESCRIPTOR.message_types_by_name['SetCustomerService'] = _SETCUSTOMERSERVICE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ping = _reflection.GeneratedProtocolMessageType('Ping', (_message.Message,), dict(
  DESCRIPTOR = _PING,
  __module__ = 'gm_pb2'
  # @@protoc_insertion_point(class_scope:PrivateProto.Ping)
  ))
_sym_db.RegisterMessage(Ping)

Pong = _reflection.GeneratedProtocolMessageType('Pong', (_message.Message,), dict(
  DESCRIPTOR = _PONG,
  __module__ = 'gm_pb2'
  # @@protoc_insertion_point(class_scope:PrivateProto.Pong)
  ))
_sym_db.RegisterMessage(Pong)

AddMoney = _reflection.GeneratedProtocolMessageType('AddMoney', (_message.Message,), dict(
  DESCRIPTOR = _ADDMONEY,
  __module__ = 'gm_pb2'
  # @@protoc_insertion_point(class_scope:PrivateProto.AddMoney)
  ))
_sym_db.RegisterMessage(AddMoney)

RetAddMoney = _reflection.GeneratedProtocolMessageType('RetAddMoney', (_message.Message,), dict(
  DESCRIPTOR = _RETADDMONEY,
  __module__ = 'gm_pb2'
  # @@protoc_insertion_point(class_scope:PrivateProto.RetAddMoney)
  ))
_sym_db.RegisterMessage(RetAddMoney)

SetNotice = _reflection.GeneratedProtocolMessageType('SetNotice', (_message.Message,), dict(
  DESCRIPTOR = _SETNOTICE,
  __module__ = 'gm_pb2'
  # @@protoc_insertion_point(class_scope:PrivateProto.SetNotice)
  ))
_sym_db.RegisterMessage(SetNotice)

SetCustomerService = _reflection.GeneratedProtocolMessageType('SetCustomerService', (_message.Message,), dict(
  DESCRIPTOR = _SETCUSTOMERSERVICE,
  __module__ = 'gm_pb2'
  # @@protoc_insertion_point(class_scope:PrivateProto.SetCustomerService)
  ))
_sym_db.RegisterMessage(SetCustomerService)


# @@protoc_insertion_point(module_scope)
